name: push

on:
  push:
    branches:
      - master

jobs:
  ssh:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true

    steps:     
      - name: Install SSH Key
        uses: shimataro/ssh-key-action/@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
          # replace / ignore / fail
          if_key_exists: fail

      - name: Update website
        run: ${{ secrets.SSH_COMMANDS }}
